// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lotto.proto

package lotto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Void struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Void) Reset()         { *m = Void{} }
func (m *Void) String() string { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()    {}
func (*Void) Descriptor() ([]byte, []int) {
	return fileDescriptor_lotto_be26443a843dad64, []int{0}
}
func (m *Void) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Void.Unmarshal(m, b)
}
func (m *Void) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Void.Marshal(b, m, deterministic)
}
func (dst *Void) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Void.Merge(dst, src)
}
func (m *Void) XXX_Size() int {
	return xxx_messageInfo_Void.Size(m)
}
func (m *Void) XXX_DiscardUnknown() {
	xxx_messageInfo_Void.DiscardUnknown(m)
}

var xxx_messageInfo_Void proto.InternalMessageInfo

type GetUserRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_lotto_be26443a843dad64, []int{1}
}
func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (dst *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(dst, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UpdateUserRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_lotto_be26443a843dad64, []int{2}
}
func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(dst, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DeleteUserRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_lotto_be26443a843dad64, []int{3}
}
func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(dst, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type AddUserRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserRequest) Reset()         { *m = AddUserRequest{} }
func (m *AddUserRequest) String() string { return proto.CompactTextString(m) }
func (*AddUserRequest) ProtoMessage()    {}
func (*AddUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_lotto_be26443a843dad64, []int{4}
}
func (m *AddUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserRequest.Unmarshal(m, b)
}
func (m *AddUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserRequest.Marshal(b, m, deterministic)
}
func (dst *AddUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserRequest.Merge(dst, src)
}
func (m *AddUserRequest) XXX_Size() int {
	return xxx_messageInfo_AddUserRequest.Size(m)
}
func (m *AddUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserRequest proto.InternalMessageInfo

func (m *AddUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the user
type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_lotto_be26443a843dad64, []int{5}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetUsersRequest struct {
	PageSize             int32    `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsersRequest) Reset()         { *m = GetUsersRequest{} }
func (m *GetUsersRequest) String() string { return proto.CompactTextString(m) }
func (*GetUsersRequest) ProtoMessage()    {}
func (*GetUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_lotto_be26443a843dad64, []int{6}
}
func (m *GetUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersRequest.Unmarshal(m, b)
}
func (m *GetUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersRequest.Marshal(b, m, deterministic)
}
func (dst *GetUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersRequest.Merge(dst, src)
}
func (m *GetUsersRequest) XXX_Size() int {
	return xxx_messageInfo_GetUsersRequest.Size(m)
}
func (m *GetUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersRequest proto.InternalMessageInfo

func (m *GetUsersRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *GetUsersRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetUserResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	NextId               string   `protobuf:"bytes,2,opt,name=next_id,json=nextId,proto3" json:"next_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_lotto_be26443a843dad64, []int{7}
}
func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (dst *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(dst, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *GetUserResponse) GetNextId() string {
	if m != nil {
		return m.NextId
	}
	return ""
}

type GetCategoriesByUserIDRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCategoriesByUserIDRequest) Reset()         { *m = GetCategoriesByUserIDRequest{} }
func (m *GetCategoriesByUserIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetCategoriesByUserIDRequest) ProtoMessage()    {}
func (*GetCategoriesByUserIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_lotto_be26443a843dad64, []int{8}
}
func (m *GetCategoriesByUserIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCategoriesByUserIDRequest.Unmarshal(m, b)
}
func (m *GetCategoriesByUserIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCategoriesByUserIDRequest.Marshal(b, m, deterministic)
}
func (dst *GetCategoriesByUserIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCategoriesByUserIDRequest.Merge(dst, src)
}
func (m *GetCategoriesByUserIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetCategoriesByUserIDRequest.Size(m)
}
func (m *GetCategoriesByUserIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCategoriesByUserIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCategoriesByUserIDRequest proto.InternalMessageInfo

func (m *GetCategoriesByUserIDRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type GetCategoryRequest struct {
	CategoryID           string   `protobuf:"bytes,1,opt,name=categoryID,proto3" json:"categoryID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCategoryRequest) Reset()         { *m = GetCategoryRequest{} }
func (m *GetCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*GetCategoryRequest) ProtoMessage()    {}
func (*GetCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_lotto_be26443a843dad64, []int{9}
}
func (m *GetCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCategoryRequest.Unmarshal(m, b)
}
func (m *GetCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCategoryRequest.Marshal(b, m, deterministic)
}
func (dst *GetCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCategoryRequest.Merge(dst, src)
}
func (m *GetCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_GetCategoryRequest.Size(m)
}
func (m *GetCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCategoryRequest proto.InternalMessageInfo

func (m *GetCategoryRequest) GetCategoryID() string {
	if m != nil {
		return m.CategoryID
	}
	return ""
}

type UpdateCategoryRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCategoryRequest) Reset()         { *m = UpdateCategoryRequest{} }
func (m *UpdateCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCategoryRequest) ProtoMessage()    {}
func (*UpdateCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_lotto_be26443a843dad64, []int{10}
}
func (m *UpdateCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCategoryRequest.Unmarshal(m, b)
}
func (m *UpdateCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCategoryRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCategoryRequest.Merge(dst, src)
}
func (m *UpdateCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCategoryRequest.Size(m)
}
func (m *UpdateCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCategoryRequest proto.InternalMessageInfo

func (m *UpdateCategoryRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateCategoryRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UpdateCategoryRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DeleteCategoryRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCategoryRequest) Reset()         { *m = DeleteCategoryRequest{} }
func (m *DeleteCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCategoryRequest) ProtoMessage()    {}
func (*DeleteCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_lotto_be26443a843dad64, []int{11}
}
func (m *DeleteCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCategoryRequest.Unmarshal(m, b)
}
func (m *DeleteCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCategoryRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCategoryRequest.Merge(dst, src)
}
func (m *DeleteCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCategoryRequest.Size(m)
}
func (m *DeleteCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCategoryRequest proto.InternalMessageInfo

func (m *DeleteCategoryRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type AddCategoryRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddCategoryRequest) Reset()         { *m = AddCategoryRequest{} }
func (m *AddCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*AddCategoryRequest) ProtoMessage()    {}
func (*AddCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_lotto_be26443a843dad64, []int{12}
}
func (m *AddCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCategoryRequest.Unmarshal(m, b)
}
func (m *AddCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCategoryRequest.Marshal(b, m, deterministic)
}
func (dst *AddCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCategoryRequest.Merge(dst, src)
}
func (m *AddCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_AddCategoryRequest.Size(m)
}
func (m *AddCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddCategoryRequest proto.InternalMessageInfo

func (m *AddCategoryRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AddCategoryRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Category struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UserId               int64    `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_lotto_be26443a843dad64, []int{13}
}
func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (dst *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(dst, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Category) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type Categories struct {
	Categories           []*Category `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Categories) Reset()         { *m = Categories{} }
func (m *Categories) String() string { return proto.CompactTextString(m) }
func (*Categories) ProtoMessage()    {}
func (*Categories) Descriptor() ([]byte, []int) {
	return fileDescriptor_lotto_be26443a843dad64, []int{14}
}
func (m *Categories) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Categories.Unmarshal(m, b)
}
func (m *Categories) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Categories.Marshal(b, m, deterministic)
}
func (dst *Categories) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Categories.Merge(dst, src)
}
func (m *Categories) XXX_Size() int {
	return xxx_messageInfo_Categories.Size(m)
}
func (m *Categories) XXX_DiscardUnknown() {
	xxx_messageInfo_Categories.DiscardUnknown(m)
}

var xxx_messageInfo_Categories proto.InternalMessageInfo

func (m *Categories) GetCategories() []*Category {
	if m != nil {
		return m.Categories
	}
	return nil
}

// Contexts
type Context struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Note                 string   `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	UserID               int64    `protobuf:"varint,4,opt,name=userID,proto3" json:"userID,omitempty"`
	CategoryID           int64    `protobuf:"varint,5,opt,name=categoryID,proto3" json:"categoryID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Context) Reset()         { *m = Context{} }
func (m *Context) String() string { return proto.CompactTextString(m) }
func (*Context) ProtoMessage()    {}
func (*Context) Descriptor() ([]byte, []int) {
	return fileDescriptor_lotto_be26443a843dad64, []int{15}
}
func (m *Context) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Context.Unmarshal(m, b)
}
func (m *Context) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Context.Marshal(b, m, deterministic)
}
func (dst *Context) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Context.Merge(dst, src)
}
func (m *Context) XXX_Size() int {
	return xxx_messageInfo_Context.Size(m)
}
func (m *Context) XXX_DiscardUnknown() {
	xxx_messageInfo_Context.DiscardUnknown(m)
}

var xxx_messageInfo_Context proto.InternalMessageInfo

func (m *Context) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Context) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Context) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *Context) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *Context) GetCategoryID() int64 {
	if m != nil {
		return m.CategoryID
	}
	return 0
}

type Contexts struct {
	Contexts             []*Context `protobuf:"bytes,1,rep,name=contexts,proto3" json:"contexts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Contexts) Reset()         { *m = Contexts{} }
func (m *Contexts) String() string { return proto.CompactTextString(m) }
func (*Contexts) ProtoMessage()    {}
func (*Contexts) Descriptor() ([]byte, []int) {
	return fileDescriptor_lotto_be26443a843dad64, []int{16}
}
func (m *Contexts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contexts.Unmarshal(m, b)
}
func (m *Contexts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contexts.Marshal(b, m, deterministic)
}
func (dst *Contexts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contexts.Merge(dst, src)
}
func (m *Contexts) XXX_Size() int {
	return xxx_messageInfo_Contexts.Size(m)
}
func (m *Contexts) XXX_DiscardUnknown() {
	xxx_messageInfo_Contexts.DiscardUnknown(m)
}

var xxx_messageInfo_Contexts proto.InternalMessageInfo

func (m *Contexts) GetContexts() []*Context {
	if m != nil {
		return m.Contexts
	}
	return nil
}

type GetContextsByCategoryIDRequest struct {
	CategoryID           string   `protobuf:"bytes,1,opt,name=categoryID,proto3" json:"categoryID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetContextsByCategoryIDRequest) Reset()         { *m = GetContextsByCategoryIDRequest{} }
func (m *GetContextsByCategoryIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetContextsByCategoryIDRequest) ProtoMessage()    {}
func (*GetContextsByCategoryIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_lotto_be26443a843dad64, []int{17}
}
func (m *GetContextsByCategoryIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContextsByCategoryIDRequest.Unmarshal(m, b)
}
func (m *GetContextsByCategoryIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContextsByCategoryIDRequest.Marshal(b, m, deterministic)
}
func (dst *GetContextsByCategoryIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContextsByCategoryIDRequest.Merge(dst, src)
}
func (m *GetContextsByCategoryIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetContextsByCategoryIDRequest.Size(m)
}
func (m *GetContextsByCategoryIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContextsByCategoryIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetContextsByCategoryIDRequest proto.InternalMessageInfo

func (m *GetContextsByCategoryIDRequest) GetCategoryID() string {
	if m != nil {
		return m.CategoryID
	}
	return ""
}

type GetContextRequest struct {
	ContextID            string   `protobuf:"bytes,1,opt,name=contextID,proto3" json:"contextID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetContextRequest) Reset()         { *m = GetContextRequest{} }
func (m *GetContextRequest) String() string { return proto.CompactTextString(m) }
func (*GetContextRequest) ProtoMessage()    {}
func (*GetContextRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_lotto_be26443a843dad64, []int{18}
}
func (m *GetContextRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContextRequest.Unmarshal(m, b)
}
func (m *GetContextRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContextRequest.Marshal(b, m, deterministic)
}
func (dst *GetContextRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContextRequest.Merge(dst, src)
}
func (m *GetContextRequest) XXX_Size() int {
	return xxx_messageInfo_GetContextRequest.Size(m)
}
func (m *GetContextRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContextRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetContextRequest proto.InternalMessageInfo

func (m *GetContextRequest) GetContextID() string {
	if m != nil {
		return m.ContextID
	}
	return ""
}

type UpdateContextRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Note                 string   `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	UserID               int64    `protobuf:"varint,4,opt,name=userID,proto3" json:"userID,omitempty"`
	CategoryID           int64    `protobuf:"varint,5,opt,name=categoryID,proto3" json:"categoryID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateContextRequest) Reset()         { *m = UpdateContextRequest{} }
func (m *UpdateContextRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateContextRequest) ProtoMessage()    {}
func (*UpdateContextRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_lotto_be26443a843dad64, []int{19}
}
func (m *UpdateContextRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateContextRequest.Unmarshal(m, b)
}
func (m *UpdateContextRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateContextRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateContextRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateContextRequest.Merge(dst, src)
}
func (m *UpdateContextRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateContextRequest.Size(m)
}
func (m *UpdateContextRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateContextRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateContextRequest proto.InternalMessageInfo

func (m *UpdateContextRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateContextRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateContextRequest) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *UpdateContextRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *UpdateContextRequest) GetCategoryID() int64 {
	if m != nil {
		return m.CategoryID
	}
	return 0
}

type DeleteContextRequest struct {
	ContextID            string   `protobuf:"bytes,1,opt,name=contextID,proto3" json:"contextID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteContextRequest) Reset()         { *m = DeleteContextRequest{} }
func (m *DeleteContextRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteContextRequest) ProtoMessage()    {}
func (*DeleteContextRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_lotto_be26443a843dad64, []int{20}
}
func (m *DeleteContextRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteContextRequest.Unmarshal(m, b)
}
func (m *DeleteContextRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteContextRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteContextRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteContextRequest.Merge(dst, src)
}
func (m *DeleteContextRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteContextRequest.Size(m)
}
func (m *DeleteContextRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteContextRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteContextRequest proto.InternalMessageInfo

func (m *DeleteContextRequest) GetContextID() string {
	if m != nil {
		return m.ContextID
	}
	return ""
}

type AddContextRequest struct {
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Note                 string   `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	UserID               int64    `protobuf:"varint,4,opt,name=userID,proto3" json:"userID,omitempty"`
	CategoryID           int64    `protobuf:"varint,5,opt,name=categoryID,proto3" json:"categoryID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddContextRequest) Reset()         { *m = AddContextRequest{} }
func (m *AddContextRequest) String() string { return proto.CompactTextString(m) }
func (*AddContextRequest) ProtoMessage()    {}
func (*AddContextRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_lotto_be26443a843dad64, []int{21}
}
func (m *AddContextRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddContextRequest.Unmarshal(m, b)
}
func (m *AddContextRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddContextRequest.Marshal(b, m, deterministic)
}
func (dst *AddContextRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddContextRequest.Merge(dst, src)
}
func (m *AddContextRequest) XXX_Size() int {
	return xxx_messageInfo_AddContextRequest.Size(m)
}
func (m *AddContextRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddContextRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddContextRequest proto.InternalMessageInfo

func (m *AddContextRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddContextRequest) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *AddContextRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *AddContextRequest) GetCategoryID() int64 {
	if m != nil {
		return m.CategoryID
	}
	return 0
}

func init() {
	proto.RegisterType((*Void)(nil), "lotto.Void")
	proto.RegisterType((*GetUserRequest)(nil), "lotto.GetUserRequest")
	proto.RegisterType((*UpdateUserRequest)(nil), "lotto.UpdateUserRequest")
	proto.RegisterType((*DeleteUserRequest)(nil), "lotto.DeleteUserRequest")
	proto.RegisterType((*AddUserRequest)(nil), "lotto.AddUserRequest")
	proto.RegisterType((*User)(nil), "lotto.User")
	proto.RegisterType((*GetUsersRequest)(nil), "lotto.GetUsersRequest")
	proto.RegisterType((*GetUserResponse)(nil), "lotto.GetUserResponse")
	proto.RegisterType((*GetCategoriesByUserIDRequest)(nil), "lotto.GetCategoriesByUserIDRequest")
	proto.RegisterType((*GetCategoryRequest)(nil), "lotto.GetCategoryRequest")
	proto.RegisterType((*UpdateCategoryRequest)(nil), "lotto.UpdateCategoryRequest")
	proto.RegisterType((*DeleteCategoryRequest)(nil), "lotto.DeleteCategoryRequest")
	proto.RegisterType((*AddCategoryRequest)(nil), "lotto.AddCategoryRequest")
	proto.RegisterType((*Category)(nil), "lotto.Category")
	proto.RegisterType((*Categories)(nil), "lotto.Categories")
	proto.RegisterType((*Context)(nil), "lotto.Context")
	proto.RegisterType((*Contexts)(nil), "lotto.Contexts")
	proto.RegisterType((*GetContextsByCategoryIDRequest)(nil), "lotto.GetContextsByCategoryIDRequest")
	proto.RegisterType((*GetContextRequest)(nil), "lotto.GetContextRequest")
	proto.RegisterType((*UpdateContextRequest)(nil), "lotto.UpdateContextRequest")
	proto.RegisterType((*DeleteContextRequest)(nil), "lotto.DeleteContextRequest")
	proto.RegisterType((*AddContextRequest)(nil), "lotto.AddContextRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LottoClient is the client API for Lotto service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LottoClient interface {
	// User CRUD
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error)
	AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*Void, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*Void, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*Void, error)
	GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	// Category CRUD
	GetCategoriesByUserID(ctx context.Context, in *GetCategoriesByUserIDRequest, opts ...grpc.CallOption) (*Categories, error)
	GetCategory(ctx context.Context, in *GetCategoryRequest, opts ...grpc.CallOption) (*Category, error)
	UpdateCategory(ctx context.Context, in *UpdateCategoryRequest, opts ...grpc.CallOption) (*Void, error)
	DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, opts ...grpc.CallOption) (*Void, error)
	AddCategory(ctx context.Context, in *AddCategoryRequest, opts ...grpc.CallOption) (*Void, error)
	// Category CRUD
	GetContextsByCategoryID(ctx context.Context, in *GetContextsByCategoryIDRequest, opts ...grpc.CallOption) (*Contexts, error)
	GetContext(ctx context.Context, in *GetContextRequest, opts ...grpc.CallOption) (*Context, error)
	UpdateContext(ctx context.Context, in *UpdateContextRequest, opts ...grpc.CallOption) (*Void, error)
	DeleteContext(ctx context.Context, in *DeleteContextRequest, opts ...grpc.CallOption) (*Void, error)
	AddContext(ctx context.Context, in *AddContextRequest, opts ...grpc.CallOption) (*Void, error)
}

type lottoClient struct {
	cc *grpc.ClientConn
}

func NewLottoClient(cc *grpc.ClientConn) LottoClient {
	return &lottoClient{cc}
}

func (c *lottoClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/lotto.Lotto/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lottoClient) AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/lotto.Lotto/AddUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lottoClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/lotto.Lotto/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lottoClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/lotto.Lotto/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lottoClient) GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/lotto.Lotto/GetUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lottoClient) GetCategoriesByUserID(ctx context.Context, in *GetCategoriesByUserIDRequest, opts ...grpc.CallOption) (*Categories, error) {
	out := new(Categories)
	err := c.cc.Invoke(ctx, "/lotto.Lotto/GetCategoriesByUserID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lottoClient) GetCategory(ctx context.Context, in *GetCategoryRequest, opts ...grpc.CallOption) (*Category, error) {
	out := new(Category)
	err := c.cc.Invoke(ctx, "/lotto.Lotto/GetCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lottoClient) UpdateCategory(ctx context.Context, in *UpdateCategoryRequest, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/lotto.Lotto/UpdateCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lottoClient) DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/lotto.Lotto/DeleteCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lottoClient) AddCategory(ctx context.Context, in *AddCategoryRequest, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/lotto.Lotto/AddCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lottoClient) GetContextsByCategoryID(ctx context.Context, in *GetContextsByCategoryIDRequest, opts ...grpc.CallOption) (*Contexts, error) {
	out := new(Contexts)
	err := c.cc.Invoke(ctx, "/lotto.Lotto/GetContextsByCategoryID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lottoClient) GetContext(ctx context.Context, in *GetContextRequest, opts ...grpc.CallOption) (*Context, error) {
	out := new(Context)
	err := c.cc.Invoke(ctx, "/lotto.Lotto/GetContext", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lottoClient) UpdateContext(ctx context.Context, in *UpdateContextRequest, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/lotto.Lotto/UpdateContext", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lottoClient) DeleteContext(ctx context.Context, in *DeleteContextRequest, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/lotto.Lotto/DeleteContext", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lottoClient) AddContext(ctx context.Context, in *AddContextRequest, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/lotto.Lotto/AddContext", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LottoServer is the server API for Lotto service.
type LottoServer interface {
	// User CRUD
	GetUser(context.Context, *GetUserRequest) (*User, error)
	AddUser(context.Context, *AddUserRequest) (*Void, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*Void, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*Void, error)
	GetUsers(context.Context, *GetUsersRequest) (*GetUserResponse, error)
	// Category CRUD
	GetCategoriesByUserID(context.Context, *GetCategoriesByUserIDRequest) (*Categories, error)
	GetCategory(context.Context, *GetCategoryRequest) (*Category, error)
	UpdateCategory(context.Context, *UpdateCategoryRequest) (*Void, error)
	DeleteCategory(context.Context, *DeleteCategoryRequest) (*Void, error)
	AddCategory(context.Context, *AddCategoryRequest) (*Void, error)
	// Category CRUD
	GetContextsByCategoryID(context.Context, *GetContextsByCategoryIDRequest) (*Contexts, error)
	GetContext(context.Context, *GetContextRequest) (*Context, error)
	UpdateContext(context.Context, *UpdateContextRequest) (*Void, error)
	DeleteContext(context.Context, *DeleteContextRequest) (*Void, error)
	AddContext(context.Context, *AddContextRequest) (*Void, error)
}

func RegisterLottoServer(s *grpc.Server, srv LottoServer) {
	s.RegisterService(&_Lotto_serviceDesc, srv)
}

func _Lotto_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LottoServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lotto.Lotto/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LottoServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lotto_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LottoServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lotto.Lotto/AddUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LottoServer).AddUser(ctx, req.(*AddUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lotto_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LottoServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lotto.Lotto/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LottoServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lotto_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LottoServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lotto.Lotto/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LottoServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lotto_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LottoServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lotto.Lotto/GetUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LottoServer).GetUsers(ctx, req.(*GetUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lotto_GetCategoriesByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoriesByUserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LottoServer).GetCategoriesByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lotto.Lotto/GetCategoriesByUserID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LottoServer).GetCategoriesByUserID(ctx, req.(*GetCategoriesByUserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lotto_GetCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LottoServer).GetCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lotto.Lotto/GetCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LottoServer).GetCategory(ctx, req.(*GetCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lotto_UpdateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LottoServer).UpdateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lotto.Lotto/UpdateCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LottoServer).UpdateCategory(ctx, req.(*UpdateCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lotto_DeleteCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LottoServer).DeleteCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lotto.Lotto/DeleteCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LottoServer).DeleteCategory(ctx, req.(*DeleteCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lotto_AddCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LottoServer).AddCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lotto.Lotto/AddCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LottoServer).AddCategory(ctx, req.(*AddCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lotto_GetContextsByCategoryID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContextsByCategoryIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LottoServer).GetContextsByCategoryID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lotto.Lotto/GetContextsByCategoryID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LottoServer).GetContextsByCategoryID(ctx, req.(*GetContextsByCategoryIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lotto_GetContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LottoServer).GetContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lotto.Lotto/GetContext",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LottoServer).GetContext(ctx, req.(*GetContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lotto_UpdateContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LottoServer).UpdateContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lotto.Lotto/UpdateContext",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LottoServer).UpdateContext(ctx, req.(*UpdateContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lotto_DeleteContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LottoServer).DeleteContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lotto.Lotto/DeleteContext",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LottoServer).DeleteContext(ctx, req.(*DeleteContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lotto_AddContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LottoServer).AddContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lotto.Lotto/AddContext",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LottoServer).AddContext(ctx, req.(*AddContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Lotto_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lotto.Lotto",
	HandlerType: (*LottoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _Lotto_GetUser_Handler,
		},
		{
			MethodName: "AddUser",
			Handler:    _Lotto_AddUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _Lotto_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _Lotto_DeleteUser_Handler,
		},
		{
			MethodName: "GetUsers",
			Handler:    _Lotto_GetUsers_Handler,
		},
		{
			MethodName: "GetCategoriesByUserID",
			Handler:    _Lotto_GetCategoriesByUserID_Handler,
		},
		{
			MethodName: "GetCategory",
			Handler:    _Lotto_GetCategory_Handler,
		},
		{
			MethodName: "UpdateCategory",
			Handler:    _Lotto_UpdateCategory_Handler,
		},
		{
			MethodName: "DeleteCategory",
			Handler:    _Lotto_DeleteCategory_Handler,
		},
		{
			MethodName: "AddCategory",
			Handler:    _Lotto_AddCategory_Handler,
		},
		{
			MethodName: "GetContextsByCategoryID",
			Handler:    _Lotto_GetContextsByCategoryID_Handler,
		},
		{
			MethodName: "GetContext",
			Handler:    _Lotto_GetContext_Handler,
		},
		{
			MethodName: "UpdateContext",
			Handler:    _Lotto_UpdateContext_Handler,
		},
		{
			MethodName: "DeleteContext",
			Handler:    _Lotto_DeleteContext_Handler,
		},
		{
			MethodName: "AddContext",
			Handler:    _Lotto_AddContext_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lotto.proto",
}

func init() { proto.RegisterFile("lotto.proto", fileDescriptor_lotto_be26443a843dad64) }

var fileDescriptor_lotto_be26443a843dad64 = []byte{
	// 686 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x96, 0x5b, 0x4f, 0x13, 0x41,
	0x14, 0xc7, 0xb3, 0xbd, 0x51, 0xfe, 0x0d, 0x4b, 0x3a, 0xa1, 0x50, 0x0b, 0x21, 0x38, 0x68, 0x24,
	0x24, 0x62, 0x04, 0xc4, 0x20, 0xd1, 0x40, 0x21, 0x12, 0x12, 0x8d, 0x5a, 0x82, 0xaf, 0xa4, 0xb2,
	0x93, 0x66, 0x13, 0xec, 0xd6, 0xee, 0x34, 0xa1, 0x7c, 0x00, 0x3f, 0xb6, 0x31, 0xb3, 0x3b, 0xd7,
	0xdd, 0x16, 0xeb, 0x83, 0xbe, 0x75, 0xce, 0x9e, 0xff, 0x99, 0x33, 0xe7, 0xf2, 0x4b, 0x51, 0xbb,
	0x8d, 0x38, 0x8f, 0x76, 0x06, 0xc3, 0x88, 0x47, 0xa4, 0x9c, 0x1c, 0x68, 0x05, 0xa5, 0xaf, 0x51,
	0x18, 0xd0, 0x0d, 0xf8, 0xe7, 0x8c, 0x5f, 0xc5, 0x6c, 0xd8, 0x61, 0x3f, 0x46, 0x2c, 0xe6, 0xc4,
	0x47, 0x21, 0x0c, 0x9a, 0xde, 0x86, 0xb7, 0x35, 0xdf, 0x29, 0x84, 0x01, 0x7d, 0x8d, 0xfa, 0xd5,
	0x20, 0xe8, 0x72, 0xf6, 0x80, 0x13, 0x21, 0x28, 0xf5, 0xbb, 0xdf, 0x59, 0xb3, 0x90, 0x58, 0x92,
	0xdf, 0x74, 0x13, 0xf5, 0x33, 0x76, 0xcb, 0x1e, 0x14, 0xd2, 0x27, 0xf0, 0x4f, 0x82, 0xc0, 0xf6,
	0x50, 0xa1, 0x3c, 0x2b, 0xd4, 0x36, 0x4a, 0xc2, 0xc5, 0x52, 0x17, 0xa7, 0x5e, 0xfb, 0x0e, 0x8b,
	0xf2, 0x45, 0xb1, 0x0a, 0xb9, 0x8a, 0xf9, 0x41, 0xb7, 0xc7, 0xae, 0xe3, 0xf0, 0x3e, 0x8d, 0x5b,
	0xee, 0x54, 0x85, 0xe1, 0x32, 0xbc, 0x67, 0x32, 0x66, 0x41, 0x67, 0xf4, 0x51, 0xeb, 0x3b, 0x2c,
	0x1e, 0x44, 0xfd, 0x98, 0x91, 0xc7, 0x28, 0x8f, 0x44, 0xbc, 0xa6, 0xb7, 0x51, 0xdc, 0xaa, 0xed,
	0xd6, 0x76, 0xd2, 0x82, 0x26, 0x3e, 0xe9, 0x17, 0xb2, 0x82, 0xb9, 0x3e, 0xbb, 0xe3, 0xd7, 0x3a,
	0x54, 0x45, 0x1c, 0x2f, 0x02, 0x7a, 0x80, 0xb5, 0x73, 0xc6, 0x4f, 0xbb, 0x9c, 0xf5, 0xa2, 0x61,
	0xc8, 0xe2, 0xf6, 0x58, 0xc8, 0x2e, 0xce, 0x54, 0x6e, 0xcb, 0xa8, 0x8c, 0x12, 0x83, 0x7c, 0xb0,
	0x3c, 0xd1, 0x7d, 0x10, 0xa3, 0x1b, 0x2b, 0xef, 0x75, 0xe0, 0x46, 0x9a, 0xb4, 0xc2, 0xb2, 0xd0,
	0x4b, 0x34, 0xd2, 0x66, 0x65, 0x85, 0xd9, 0x86, 0xa9, 0x6b, 0x75, 0xba, 0xe9, 0x49, 0x57, 0xb4,
	0x68, 0x55, 0xf4, 0x19, 0x1a, 0x69, 0x23, 0xff, 0x10, 0x94, 0x1e, 0x83, 0x9c, 0x04, 0x41, 0xd6,
	0xcb, 0x5c, 0xe5, 0x4d, 0xbc, 0xca, 0x6e, 0xde, 0x7b, 0x54, 0x95, 0x7c, 0x96, 0x66, 0x5b, 0xb1,
	0x8b, 0x89, 0x9f, 0x3c, 0xd1, 0xb7, 0x80, 0x29, 0x39, 0x79, 0xa1, 0xab, 0x16, 0x32, 0xd5, 0xc4,
	0x45, 0xd9, 0x44, 0x9d, 0xad, 0xe5, 0x42, 0xc7, 0x98, 0x3b, 0x8d, 0xfa, 0x9c, 0xdd, 0xf1, 0x99,
	0xb2, 0x10, 0xb6, 0x88, 0x9b, 0xa2, 0x45, 0x9c, 0x59, 0x7d, 0x2d, 0x59, 0x99, 0x9d, 0x65, 0x3a,
	0x58, 0x4e, 0xbe, 0xd9, 0x1d, 0x3c, 0x40, 0x55, 0x5e, 0x1d, 0x93, 0x6d, 0x54, 0x6f, 0xe4, 0x6f,
	0x99, 0xb5, 0xaf, 0xb2, 0x4e, 0xcd, 0x1d, 0xfd, 0x9d, 0x1e, 0x63, 0x5d, 0xcc, 0x8b, 0x3c, 0xb6,
	0xc7, 0xa7, 0x3a, 0xe4, 0xac, 0xb3, 0xf3, 0x12, 0x75, 0x13, 0x41, 0x89, 0xd6, 0x30, 0x2f, 0xaf,
	0xd0, 0x1a, 0x63, 0xa0, 0x3f, 0x3d, 0x2c, 0xc9, 0x79, 0x73, 0x65, 0xff, 0xbb, 0x6a, 0xfb, 0x58,
	0x92, 0x23, 0xfa, 0x37, 0xe9, 0xc7, 0xa8, 0x8b, 0x79, 0x75, 0x25, 0xff, 0x38, 0xd5, 0xdd, 0x5f,
	0x15, 0x94, 0x3f, 0x88, 0x26, 0x92, 0xe7, 0x98, 0x93, 0xa4, 0x21, 0x0d, 0xd9, 0x57, 0x97, 0xc5,
	0x2d, 0x9b, 0x34, 0xc2, 0x5d, 0xa2, 0x52, 0xbb, 0xbb, 0xe8, 0xd4, 0xee, 0x82, 0xec, 0x64, 0x0f,
	0x30, 0xdc, 0x26, 0x4d, 0x15, 0x29, 0x8b, 0xf2, 0x9c, 0xc8, 0x30, 0x5b, 0x8b, 0x72, 0x18, 0x77,
	0x45, 0x6f, 0x50, 0x55, 0xc4, 0x25, 0xcb, 0xee, 0x43, 0x14, 0x82, 0x5b, 0xcb, 0xd9, 0x07, 0x4a,
	0xb4, 0x7e, 0x42, 0x63, 0x22, 0x1e, 0xc9, 0xa6, 0x11, 0x4c, 0x85, 0x67, 0xab, 0xee, 0x2e, 0xb1,
	0xd8, 0xf5, 0x43, 0xd4, 0x2c, 0x6e, 0x92, 0x47, 0xb9, 0x30, 0x8a, 0x4b, 0xad, 0x2c, 0x01, 0xc8,
	0x11, 0x7c, 0x17, 0x9e, 0x64, 0xcd, 0xa9, 0x5a, 0x36, 0x80, 0x53, 0x84, 0x23, 0xf8, 0x2e, 0x24,
	0xb5, 0x78, 0x22, 0x3b, 0x5d, 0xf1, 0x2b, 0xd4, 0x2c, 0x70, 0xea, 0xa4, 0xf3, 0x30, 0x75, 0x65,
	0x5f, 0xb0, 0x32, 0x65, 0xe7, 0xc9, 0x53, 0xeb, 0xdd, 0xd3, 0x99, 0x60, 0x6a, 0xa0, 0x90, 0x73,
	0x00, 0x18, 0x89, 0x1e, 0x80, 0x1c, 0x17, 0x5a, 0x19, 0x10, 0x91, 0x43, 0x2c, 0x38, 0x20, 0x20,
	0xab, 0x6e, 0xe9, 0x5c, 0xb5, 0xf3, 0x8a, 0x43, 0x2c, 0x38, 0xbb, 0xab, 0xa5, 0x93, 0x36, 0x3a,
	0x37, 0xae, 0x66, 0x81, 0x75, 0xb6, 0xb9, 0x9d, 0x76, 0x44, 0xed, 0x26, 0x16, 0xc2, 0x68, 0xa7,
	0x37, 0x1c, 0xdc, 0xa4, 0xd6, 0x76, 0xba, 0x8e, 0x9f, 0xbd, 0x6f, 0x95, 0xe4, 0x2f, 0xd2, 0xde,
	0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x0b, 0xec, 0xdf, 0x31, 0x09, 0x00, 0x00,
}
